### ISSUE TITLE
microsoft language server indexing entire home directory

### ISSUE THREAD

**Issue by sehnsucht13** [emacs-lsp/lsp-python-ms#29]
Just a quick question in regards to the server. 

Whenever I use this server, it begins to index my entire home directory(I have the source code for some large python projects). For example, If I have the following directory layout
-Project Directory
 ---Large Pyhon project
 ---Another Large project
 ---Project I am currently working on
the server will end up indexing those projects as well which makes it very slow to start and to respond as well. Is there any way of preventing this? Should I begin to use pip environments for my smaller projects as well? 

Thank you in advance and thank you to everybody who has worked on this.

**Comment by seagle0128** [comment]
Are you using `projectile` or `project` in your Emacs env? `lsp-mode` leverages `projectile/project` to guess the project root. If your project is a VC-controlled one (e.g. git), `lsp-mode` should be able to guess the project root is `Large Pyhon project`, otherwise you need to add one specific file to indicate thr project root , e.g. `.projectile`.

This question is not related to `mspyls` or `lsp-python-ms`, while a common question for `lsp-mode`, IMO.

**Comment by muffinmad** [comment]
Discussion about passing `nil` as `rootPath`: https://github.com/emacs-lsp/lsp-mode/issues/515#issuecomment-509693361

And feature request: https://github.com/emacs-lsp/lsp-mode/issues/944

**Comment by seagle0128** [comment]
Close it due to inactivity.
Please track the upstream (`lsp-mode`).
