### ISSUE TITLE
Symbol highlighting

### ISSUE THREAD

**Issue by astenman** [emacs-lsp/lsp-python-ms#62]
When I put the cursor over a symbol, it does not highlight the other occurrences in the buffer (as it does in other LSP supported languages). Is this a configuration error, or is this functionality missing from the Microsoft language server?

**Comment by seagle0128** [comment]
I believe it's not the functionality of `lsp-python-ms` or `lsp-mode`. I am using the amazing package [symbol-overlay](https://github.com/wolray/symbol-overlay).

**Comment by astenman** [comment]
I am absolutely convinced that this is a functionality of lsp-mode, because in an LSP enabled PHP buffer I get the look according to the image below ...

![lsp-php](https://user-images.githubusercontent.com/43724994/66134192-3a0b9b00-e5f8-11e9-9a23-7a58171bdb96.png)

**Comment by seagle0128** [comment]
I quickly review the codes of `lsp-mode`. I withdraw my comments above and apologize. `lsp-mode` supports symbol-highlighting as long as the LSP server implemented it, while semantic-highlighting is not yet part of the official LSP spec.

I am thinking it may be a configuration issue, because VSCode supports this feature with mspyls according to my checking. But I am not very sure, perhaps @yyoncho can figure out it.

**Comment by seagle0128** [comment]
I went through the codes of [mspyls](https://github.com/microsoft/python-language-server), and found `documentHighlightProvider` is not set. That means symbol-highlighting is not supported. The symbol-highlighting in VSCode is similar with `symbol-overlay`, not from LSP.

**Comment by yyoncho** [comment]
@astenman  For future reference, you may use `M-x lsp-describe-session` and then expand the server capabilities node.
